<?php

/**
 * PluginSpeedMonitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSpeedMonitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSpeedMonitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSpeedMonitor');
    }
}