<?php

/**
 * PluginspeedLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginspeedLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginspeedLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginspeedLog');
    }
}